indexing-settings:
  sites:
    - url: https://ipfran.ru/
      name: Ипфран.ру
    - url: https://nikoartgallery.com/
      name: Галерея.ру
    - url: https://dimonvideo.ru/
      name:  ДимонВидео.ру

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: SQLTrying4488
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # ⚠️ НЕ create! Теперь данные сохраняются
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc.time_zone: UTC  # ⚡ Исправляет возможные проблемы с датами

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
